### ISSUE TITLE
About experiments code

### ISSUE THREAD

**Issue by OE-Heart** [lupantech/ScienceQA#1]
Hey, I think your work is very meaningful, and I found in the paper that you experimented on the UnifiedQA model, but this part of the code is not currently available in the repo.
Will you release the code next?

**Comment by lupantech** [comment]
Hi Yixin,

Thank you for being interested in our work!

The codes we used for the baselines including UnifiedQA and VQA methods are publicly available. So we have no plan to release the codes regarding the baselines we performed in the experiments. 

Best regards,
Pan
