### ISSUE TITLE
Prompt in zero-shot setting.

### ISSUE THREAD

**Issue by sunanhe** [lupantech/ScienceQA#10]
Hi, nice work! 
My questions are what is the prompt for GPT-3 zero-shot setting and how to ensure that the output of the model conforms to the parsable form.

**Comment by lupantech** [comment]
Hi, thanks for your kind words!

We followed the paper [Large Language Models are Zero-Shot Reasoners](https://arxiv.org/pdf/2205.11916.pdf) and prompted GPT-3 "Let’s think step by step" to generate a solution first, and then prompted the GPT-3 model to extract the final answer.

**Comment by sunanhe** [comment]
Thanks for your timely reply!
