### ISSUE TITLE
Questions about the process of dataset building

### ISSUE THREAD

**Issue by Richar-Du** [lupantech/ScienceQA#11]
Thanks for your awesome work! It paves the way towards multimodal reasoning agents. I noticed that the questions are collected from IXL learning. Since IXL learning is a website, would you mind explaining in detail how do you get the data from it? And the details you process the crawled data? 

Thanks in advance :)

**Comment by lupantech** [comment]
Thank you so much for expressing interest in our work and for the positive feedback on ScienceQA. We're thrilled to hear that it's contributing value to various research projects in the community.

For detailed information on the dataset collection, kindly refer to Section A.1, found on page 16 of our paper. Here's the link for your convenience: https://lupantech.github.io/papers/neurips22_scienceqa.pdf.

Best Regards,
Pan
