### ISSUE TITLE
Question about "context" in the data set

### ISSUE THREAD

**Issue by Zhudongsheng75** [lupantech/ScienceQA#14]
![image](https://github.com/lupantech/ScienceQA/assets/59612926/ba8d85d4-967d-4a63-bea9-1f13c9518e8d)

First of all, thank you for open source a very good dataset. 

There is the above image on your official website, and I am a little confused about the "context" in the red box. I didn't find the relevant keys in the "problems.json" file you provided. Can you tell me which parts make up "context" ？

I would like to incorporate your dataset into my multimodal work.  I would be very grateful if you could reply.

**Comment by lupantech** [comment]
The textual 'context' corresponds to the 'hint' attribute in the data examples found in 'problems.json'. The visual 'context' pertains to the image indicated by the 'image' attribute in the same file.

We've updated the README file for enhanced clarity regarding the attributes of the examples in 'problems.json'. You can view these updates at https://github.com/lupantech/ScienceQA/blob/main/README.md#ghost-download-the-dataset.

Thank you so much for your valuable feedback!
