### ISSUE TITLE
The image format is dict not PIL.

### ISSUE THREAD

**Issue by kai-wen-yang** [lupantech/ScienceQA#15]
Hi, I load the dataset using the following command:

```
data = datasets.load_dataset('derek-thomas/ScienceQA', 'test')
for sample in data['test']:
      sample['image']
```

But the sample['image'] in the data is the format of a dictionary with keys of 'bytes' and 'path', which is not a PIL image. And I don't know how to process it.

**Comment by lupantech** [comment]
We have uploaded a demo to illustrate how to access the ScienceQA dataset on Hugging Face, available at https://github.com/lupantech/ScienceQA/blob/main/demos/Hugging_Face_Dataset_demo.ipynb.

Alternatively, you can download ScienceQA from [Google Drive](https://drive.google.com/drive/folders/1w8imCXWYn2LxajmGeGH_g5DaL2rabHev?usp=sharing) and obtain the PNG format for the image data.
