### ISSUE TITLE
Request to add Honeybee results to the leaderboard

### ISSUE THREAD

**Issue by khanrc** [lupantech/ScienceQA#18]
Hello,

Thank you for this great project.

Could you add the results of [Honeybee](https://arxiv.org/abs/2312.06742)? (code: https://github.com/kakaobrain/honeybee)
<img width="751" alt="image" src="https://github.com/lupantech/ScienceQA/assets/3657248/1d4a1bef-4d5e-4da6-85d4-7941d95d025b">

Both results are based on the 13B models.

Thanks!

**Comment by lupantech** [comment]
Thannk you! We have recently updated the leaderboard by adding plenty of recent models, including Honeybee, at https://scienceqa.github.io/leaderboard.html. Congratulations to Honeybee for ranking third place!
