### ISSUE TITLE
Google drive link

### ISSUE THREAD

**Issue by KimWu1994** [lupantech/ScienceQA#2]
It seems that the link of Google Drive cannot be downloaded, is there a download link of one drive?

**Comment by lupantech** [comment]
Hi, 

I was wondering if you have a technical issue downloading the Google Drive files. If so, an alternative solution is to download the image data of ScienceQA by running:
```
. tools/download.sh
```
It will download the dataset from the Amazon AWS cloud.

If you have any further questions, please let me know.

Sincerely,
Pan
