### ISSUE TITLE
Not able to download dataset via Google Drive

### ISSUE THREAD

**Issue by souradipp76** [lupantech/ScienceQA#22]
The google drive link (https://drive.google.com/drive/folders/1w8imCXWYn2LxajmGeGH_g5DaL2rabHev) is not working. Showing 404 not found error.

**Comment by lupantech** [comment]
The link has been fixed. The data is avaialble at https://drive.google.com/drive/folders/16kuhXdM-MOhYcFIyRj91WvnDnjnF-xHw?usp=sharing now.
