### ISSUE TITLE
AWS Dataset is missing some images

### ISSUE THREAD

**Issue by datavistics** [lupantech/ScienceQA#4]
I believe the AWS train dataset is missing 24, but google drive had it.

**Comment by datavistics** [comment]
Or its possible it got corrupted in my download, but if someone wants to double check, that would be good.

**Comment by lupantech** [comment]
Hello,

I downloaded and checked the AWS train dataset using the following commands:

```
wget https://scienceqa.s3.us-west-1.amazonaws.com/images/train.zip

unzip -q train.zip
```

The download and extraction processes were successful, and the dataset appears to contain 24 items. Would you please try downloading it again? If it still misses 24, please let me know. Thanks a lot!
