### ISSUE TITLE
Add Multimodal-CoT results to Leaderbord page

### ISSUE THREAD

**Issue by EwoutH** [lupantech/ScienceQA#5]
It would be great if the [Multimodal-CoT](https://github.com/amazon-science/mm-cot) model ([paper](https://arxiv.org/abs/2302.00923)) could be added to the [Leaderbord](https://scienceqa.github.io/leaderboard.html) page.

![Screenshot_87](https://user-images.githubusercontent.com/15776622/220637181-dac87a04-33db-4c58-a7bb-a8bad6f8dea8.png)

**Comment by lupantech** [comment]
Absolutely! I've added the two best methods you provided to the page. 

By the way, I was wondering if it's possible to include a link to my homepage (https://lupantech.github.io/) in the Acknowledgement section of the [Multimodal-CoT](https://github.com/amazon-science/mm-cot) repository when referencing me.

Thanks!

**Comment by EwoutH** [comment]
Thanks!

Not the author, but they're probably open to a PR.
