### ISSUE TITLE
Question about lecture

### ISSUE THREAD

**Issue by lonestar234028** [lupantech/ScienceQA#6]
Hi expert, I've looked at the problems.json, the lecture looks not reasonable, how the lecture is generated? for example: for qid 5, the lecture is  `People can use the engineering-design process to develop solutions to problems. One step in the process is testing if a potential solution meets the requirements of the design. How can you determine what a test can show? You need to figure out what was tested and what was measured.nImagine an engineer needs to design a bridge for a windy location. She wants to make sure the bridge will not move too much in high wind. So, she builds a smaller prototype, or model, of a bridge. Then, she exposes the prototype to high winds and measures how much the bridge moves.nFirst, identify what was tested. A test can examine one design, or it may compare multiple prototypes to each other. In the test described above, the engineer tested a prototype of a bridge in high wind.nThen, identify what the test measured. One of the criteria for the bridge was that it not move too much in high winds. The test measured how much the prototype bridge moved.nTests can show how well one or more designs meet the criteria. The test described above can show whether the bridge would move too much in high winds..",`
However, the question is something about Gordon's test

**Comment by lupantech** [comment]
Thank you for your interest in our work and for reaching out to us. We would like to explain that the lecture is included in raw data, including the question, context, answer, and explanation. As we highlighted in our paper, the lecture serves as fundamental background knowledge, whereas the explanation offers a specific solution to arrive at the final answer.

**Comment by lonestar234028** [comment]
@lupantech Thank you for your guidance, you have been so helpful.
