### ISSUE TITLE
Sometimes the images are not related to the question at all

### ISSUE THREAD

**Issue by lonestar234028** [lupantech/ScienceQA#7]
Hi expert, is it by design?
For example, the picture is only some green plats in the small strays, but the real way to solve the problem counts on the language understanding.
`"180":{
    "question":"Which of the following was a dependent variable in this experiment?",
    "choices":[
      "the temperature of the heating pad",
      "the number of days until a seed germinated"
    ],
    "answer":1,
    "hint":"The passage below describes an experiment. Read the passage and think about the variables that are described.\n\nKenneth wanted to grow cucumbers from seeds. He read that using a heating pad to heat up potting soil could help make seeds germinate, or sprout, faster. Kenneth wondered whether the temperature of the heating pad would affect how quickly the seeds germinated.\nKenneth prepared two potting trays, each made up of ten small pots of soil. He planted one cucumber seed in each small pot and arranged the potting trays near a sunny window. He set an electric heating pad to 75\u00b0F and placed it under one potting tray. He set a second heating pad to 85\u00b0F and placed it under the other potting tray. Kenneth observed the pots daily, and he counted the number of days it took until a seed germinated in each pot.\nHint: An independent variable is a variable whose effect you are investigating. A dependent variable is a variable that you measure.\nFigure: germinating plants in a potting tray.",
    "image":"image.png",
    "task":"closed choice",
    "grade":"grade6",
    "subject":"natural science",
    "topic":"science-and-engineering-practices",
    "category":"Designing experiments",
    "skill":"Identify independent and dependent variables",
    "lecture":"Experiments have variables, or parts that change. You can design an experiment to find out how one variable affects another variable. For example, imagine that you want to find out if fertilizer affects the number of tomatoes a tomato plant grows. To answer this question, you decide to set up two equal groups of tomato plants. Then, you add fertilizer to the soil of the plants in one group but not in the other group. Later, you measure the effect of the fertilizer by counting the number of tomatoes on each plant.\nIn this experiment, the amount of fertilizer added to the soil and the number of tomatoes were both variables.\nThe amount of fertilizer added to the soil was an independent variable because it was the variable whose effect you were investigating. This type of variable is called independent because its value does not depend on what happens after the experiment begins. Instead, you decided to give fertilizer to some plants and not to others.\nThe number of tomatoes was a dependent variable because it was the variable you were measuring. This type of variable is called dependent because its value can depend on what happens in the experiment.",
    "solution":"",
    "split":"test"
  },`

**Comment by lupantech** [comment]
Thank you for your interest in our work and for reaching out to us. As we claimed in the paper, one of the key characteristics of ScienceQA is its diverse question features, particularly the **various visual context formats** that are included. Specifically, questions may or may not include an image context, and if they do, that context could be in the form of a natural image, a figure, or a plot. Depending on the question, the image context may be critical for accurate answering, or it may simply provide complementary information. This feature of ScienceQA is designed to closely align with real-world visual-language reasoning scenarios. 

We are optimistic that a perfect model will be general enough to determine how to effectively leverage this diverse visual information to improve question answering accuracy.
