### ISSUE TITLE
Topic-level evaluation result

### ISSUE THREAD

**Issue by PhanTask** [lupantech/ScienceQA#9]
Hi, this is a great dataset. Thanks for the hard work.

Instead of subject-level result, I am interested in topic-level evaluation result such as biology, chemistry, etc, and thus I wonder:

1. How do I compute accuracy for topic level?
2. Do the models on the leaderboard provide topic-level results or provide the raw result files so that people can compute topic-level accuracy for them?

Thanks.

**Comment by TonyXia2001** [comment]
Sorry about the delay of reply. I have updated the script to report topic-level evaluation results.
